version: "3.9"
services:
  jupyter:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AZ_ACCESS_TOKEN: ${AZ_ACCESS_TOKEN}
      DIGITALOCEAN_ACCESS_TOKEN: ${DIGITALOCEAN_ACCESS_TOKEN}
      OKTA_API_TOKEN: ${OKTA_API_TOKEN}
      NETLIFY_AUTH_TOKEN: ${NETLIFY_AUTH_TOKEN}
      SUMOLOGIC_ACCESSID: ${SUMOLOGIC_ACCESSID}
      SUMOLOGIC_ACCESSKEY: ${SUMOLOGIC_ACCESSKEY}
      STACKQL_GITHUB_USERNAME: ${STACKQL_GITHUB_USERNAME}
      STACKQL_GITHUB_PASSWORD: ${STACKQL_GITHUB_PASSWORD}
      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
    dns: 
      - 8.8.8.8
    command:
      - /bin/sh
      - -c
      - |
        /scripts/entrypoint.sh
    ports:
      - 8888:8888