version: "3.9"
services:
  jupyter:
    build: .
    environment:
      AUTH_STR: ${AUTH_STR}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AZ_ACCESS_TOKEN: ${AZ_ACCESS_TOKEN}
      GITHUB_CREDS: ${GITHUB_CREDS}
      OKTA_SECRET_KEY: ${OKTA_SECRET_KEY}
      NETLIFY_TOKEN: ${NETLIFY_TOKEN}
    command:
      - /bin/sh
      - -c
      - |
        /srv/stackql/stackql --version
        nohup /srv/stackql/stackql --auth="${AUTH_STR}" --pgsrv.port=5444 srv &>/dev/null &
        start-notebook.sh --NotebookApp.token=''
    ports:
      - 8888:8888 
