version: "3.9"
services:
  jupyter:
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AZ_ACCESS_TOKEN: ${AZ_ACCESS_TOKEN}
      GITHUB_CREDS: ${GITHUB_CREDS}
      OKTA_SECRET_KEY: ${OKTA_SECRET_KEY}
      NETLIFY_TOKEN: ${NETLIFY_TOKEN}
      SUMO_CREDS: ${SUMO_CREDS}
    command:
      - /bin/sh
      - -c
      - |
        /scripts/entrypoint.sh
    ports:
      - 8888:8888 